version: '3'
services:
  mysql:
    # 镜像名
    image: mysql:8.0.29
    #容器名
    container_name: mysql_master
    # 环境变量
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Shanghai
      - MYSQL_CHARSET = utf8mb4
    # 端口
    ports:
      - "3306:3306"
    # 开启root权限
    privileged: true
    # 重启策略
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
#      - /opt/nginx/nginx.conf:/etc/nginx/nginx.conf
#      - /opt/nginx/conf.d:/etc/nginx/conf.d
      - /opt/nginx/html:/usr/share/nginx/html
      # - 宿主机的路径: 容器内的路径
    ports:
      - "80:80"
    restart: always

  mysql_01:
      # 镜像名
      image: mysql:8.0.29
      #容器名
      container_name: mysql_master_01
      # 环境变量
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - TZ=Asia/Shanghai
        - MYSQL_CHARSET = utf8mb4
      # 端口
      ports:
        - "3307:3306"
      # 开启root权限
      privileged: true
      # 重启策略
      restart: always

  nginx_01:
      image: nginx:latest
      container_name: nginx_01
      volumes:
#        - /opt/nginx/nginx.conf:/etc/nginx/nginx.conf
#        - /opt/nginx/conf.d:/etc/nginx/conf.d
        - /opt/nginx/html:/usr/share/nginx/html
        # - 宿主机的路径: 容器内的路径
      ports:
        - "81:80"
      restart: always


